language: R
sudo: true
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

repos:
  CRAN: https://cran.rstudio.com/
  KRAN: http://rweb.crmda.ku.edu/kran/
  RFOG: http://R-Forge.R-project.org/

pandoc_version: 1.17.2

before_install:
- npm install netlify-cli -g
- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install -y libudunits2-dev libproj-dev libgeos++-dev libgdal-dev libv8-dev

script:
- Rscript -e 'bookdown::render_book("index.rmd", "jayhawkdown::thesis_pdf")'
- Rscript -e 'bookdown::render_book("index.rmd", "bookdown::gitbook")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
