language: R
sudo: false
cache:
  packages: true
  directories:
  - _bookdown_files
  - $HOME/.npm

repos:
  CRAN: https://cran.rstudio.com/
  KRAN: http://rweb.crmda.ku.edu/kran/
  RFOG: http://R-Forge.R-project.org/

pandoc_version: 1.19.2.1

before_install:
- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.rmd", "jayhawkdown::thesis_pdf")'
- Rscript -e 'bookdown::render_book("index.rmd", "bookdown::gitbook")'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFY_PAT
  skip_cleanup: true
